"""E2E tests for the journey a real published release leaves behind.

Spec: conceptual-workflows-init-reconcile
(lore codex show conceptual-workflows-init-reconcile)

`tests/e2e/test_init_reconcile.py` covers the upgrade a project reaches by
passing every flag. This file covers the upgrade nobody passes flags to, which
is the one an AI coding agent performs: `lore init` through a pipe, with no
terminal to prompt at and no answer recorded in `.lore/config.toml` — because
no release before this one wrote any.

The project under test is built the way the pre-manifest releases left one, and
then the historical-hash table is told what those bytes were. Both are
constructed rather than installed: no previously released wheel is available to
a test run, and `reconcile._read_legacy_payload` is the seam that module
documents for exactly this. Everything downstream of the table — the walk, the
hash test, the removals, the pruning — is the real thing.

Per decisions-006-no-seed-content-tests nothing here pins the wording of a file
under `src/lore/defaults/`. Skill ids and retirement successors are read from
the catalogue at run time.
"""

from __future__ import annotations


import shutil
from pathlib import Path

import pytest
from click.testing import CliRunner

from lore import manifest, reconcile, skills


CLAUDE_SKILLS = ".claude/skills"
LORE_SKILLS = ".lore/skills"
AGENT_DOC = ".lore/LORE-AGENT.md"

OLD_AGENT_DOC = "# Lore\n\nThe agent instructions a release before this one shipped.\n"
OLD_SKILLS_GITIGNORE = "# Auto-generated by `lore init`.\nexplore-codex/\nnew-doctrine/\n"


# ---------------------------------------------------------------------------
# Catalogue lookups — structure, never wording
# ---------------------------------------------------------------------------


def retired_alias(skill_id: str) -> str:
    """A retired skill id the catalogue records as having become *skill_id*."""
    ledger = skills.load_catalogue().get("retired", {})
    aliases = sorted(old for old, row in ledger.items() if row["into"] == skill_id)
    assert aliases, f"the catalogue records no retired skill that became {skill_id}"
    return aliases[0]


def ledger_successor(skill_id: str) -> str:
    """The skill the catalogue says replaced *skill_id*."""
    retirement = skills.retirement_for(skill_id)
    assert retirement is not None, f"{skill_id} is not in the retirement ledger"
    return retirement.into


def current_skill_ids() -> tuple[str, ...]:
    """Every skill this release ships, from the catalogue."""
    return tuple(sorted(skills.skills_in_families(skills.family_ids())))


ALIASED = ("update-doctrine", "retrieve-memory", "store-memory")
"""The current skills the fixtures rewind — a rename, a merge, and a merge that
ships reference files, which is what puts a nested directory in the sweep."""


# ---------------------------------------------------------------------------
# Running the CLI
# ---------------------------------------------------------------------------


def init(runner: CliRunner, *args: str):
    """Run `lore init` with *args* and assert it succeeded."""
    from lore.cli import main

    result = runner.invoke(main, ["init", *args])
    assert result.exit_code == 0, result.output
    return result


def entries(project_dir: Path, root: str) -> set[str]:
    """The directory names directly under *root*, excluding dotfiles."""
    base = project_dir / root
    if not base.is_dir():
        return set()
    return {child.name for child in base.iterdir() if not child.name.startswith(".")}


def removals(output: str) -> dict[str, str | None]:
    """Every ``Removed <path> — <reason>`` line, as ``path -> reason``."""
    reported: dict[str, str | None] = {}
    for line in output.splitlines():
        parts = line.split()
        if parts[:1] != ["Removed"]:
            continue
        reason = line.split("—", 1)[1].strip() if "—" in line else None
        reported[parts[1]] = reason
    return reported


def kept(output: str) -> dict[str, str | None]:
    """Every ``! Kept <path>`` report, as ``path -> the detail line under it``."""
    lines = output.splitlines()
    reported: dict[str, str | None] = {}
    for index, line in enumerate(lines):
        parts = line.split()
        if parts[:2] != ["!", "Kept"]:
            continue
        follower = lines[index + 1].strip() if index + 1 < len(lines) else ""
        detail = (
            follower if follower and not follower.startswith(("!", "Removed")) else None
        )
        reported[parts[2]] = detail
    return reported


def written(output: str) -> set[str]:
    """Every path a run reported creating or updating."""
    return {
        line.split()[1]
        for line in output.splitlines()
        if line.split()[:1] in (["Created"], ["Updated"])
    }


def shown(path: str) -> str:
    """A repo-relative path as the applied-run messages name it."""
    return path[len(".lore/") :] if path.startswith(".lore/") else path


PLAN_LABELS = ("Create", "Section", "Overwrite", "Remove", "Conflict", "Seed")


def plan_paths(output: str) -> set[str]:
    """Every path the plan's listing names, whichever block it is in."""
    return {
        line.split()[1]
        for line in output.splitlines()
        if line.startswith("  ") and line.split()[:1] and line.split()[0] in PLAN_LABELS
    }


# ---------------------------------------------------------------------------
# Building the project a pre-manifest release left behind
# ---------------------------------------------------------------------------


def age_skills(project_dir: Path, aliases: dict[str, str]) -> None:
    """Rename each installed skill directory to the retired id that became it."""
    for current, retired in aliases.items():
        source = project_dir / LORE_SKILLS / current
        assert source.is_dir(), f"{current} is not installed at {source}"
        shutil.move(str(source), str(project_dir / LORE_SKILLS / retired))


def strip_recorded_answers(project_dir: Path) -> None:
    """Remove the four recorded answers, as a pre-0.10.0 `config.toml` has none."""
    config = project_dir / ".lore" / "config.toml"
    kept_lines = [
        line
        for line in config.read_text(encoding="utf-8").splitlines(keepends=True)
        if not line.split("=", 1)[0].strip().startswith("init-")
    ]
    config.write_text("".join(kept_lines), encoding="utf-8")


def hash_tree(project_dir: Path, root: str) -> dict[str, list[str]]:
    """The historical-hash rows for everything under *root*, keyed as installed."""
    base = project_dir / root
    rows: dict[str, list[str]] = {}
    for candidate in sorted(base.rglob("*")):
        if not candidate.is_file():
            continue
        within = candidate.relative_to(base).as_posix()
        rows[f"{LORE_SKILLS}/{within}"] = [manifest.file_digest(candidate)]
    return rows


@pytest.fixture()
def fresh(tmp_path, monkeypatch):
    """An empty directory that is the working directory for the whole test."""
    monkeypatch.chdir(tmp_path)
    return tmp_path


@pytest.fixture()
def legacy_table(monkeypatch):
    """Substitute the packaged historical-hash table for one test."""

    def install(files: dict[str, list[str]]) -> None:
        payload = {"legacy_hashes_version": 1, "files": files}
        monkeypatch.setattr(reconcile, "_read_legacy_payload", lambda: payload)
        reconcile.load_legacy_hashes.cache_clear()

    yield install
    reconcile.load_legacy_hashes.cache_clear()


@pytest.fixture()
def table_rows():
    """The historical-hash rows the test has told the table about, so far."""
    return {}


@pytest.fixture()
def legacy(runner, fresh, legacy_table, table_rows):
    """A project in the state a release before the manifest left it.

    Installed under `.lore/skills/` on the pre-consolidation skill ids, with no
    `.install-manifest.json`, no recorded answers and its own agent doc and
    skills gitignore at bytes only the historical table knows.
    """
    init(runner, "--agent", "none", "--skills", "all", "--access", "native", "--yes")
    age_skills(fresh, {current: retired_alias(current) for current in ALIASED})

    (fresh / AGENT_DOC).write_text(OLD_AGENT_DOC, encoding="utf-8")
    (fresh / LORE_SKILLS / ".gitignore").write_text(
        OLD_SKILLS_GITIGNORE, encoding="utf-8"
    )
    (fresh / ".lore" / ".install-manifest.json").unlink()
    strip_recorded_answers(fresh)

    table_rows.update(hash_tree(fresh, LORE_SKILLS))
    table_rows[AGENT_DOC] = [manifest.file_digest(fresh / AGENT_DOC)]
    legacy_table(table_rows)
    return fresh


@pytest.fixture()
def hand_copied(legacy):
    """`legacy`, with `.lore/skills/` copied into `.claude/skills/`.

    The pre-feature `GETTING-STARTED.md` told people to run
    `cp -r .lore/skills/. .claude/skills/`, so this is the layout the
    documentation produced and the one the upgrade has to survive.
    """
    shutil.copytree(legacy / LORE_SKILLS, legacy / CLAUDE_SKILLS)
    return legacy


# ---------------------------------------------------------------------------
# The worst one — no answer at all must never uninstall
# ---------------------------------------------------------------------------


class TestNoAgentAnswerNeverUninstalls:
    """`lore init` with no flags, no terminal and no recorded answer.

    "Nobody said which agents" is not "the user asked for no agent". The first
    is the state every pre-0.10.0 project is in; reading it as the second
    deletes every skill the documented `cp -r` put in `.claude/skills/`.
    """

    def test_the_agent_directory_is_not_emptied(self, runner, hand_copied):
        init(runner)
        assert entries(hand_copied, CLAUDE_SKILLS)

    def test_every_current_skill_is_installed_into_the_agent_directory(
        self, runner, hand_copied
    ):
        init(runner)
        assert entries(hand_copied, CLAUDE_SKILLS) == set(current_skill_ids())

    def test_every_retired_skill_is_gone_from_the_agent_directory(
        self, runner, hand_copied
    ):
        init(runner)
        installed = entries(hand_copied, CLAUDE_SKILLS)
        for current in ALIASED:
            assert retired_alias(current) not in installed

    def test_the_agent_instruction_file_is_written(self, runner, hand_copied):
        init(runner)
        assert (hand_copied / "CLAUDE.md").is_file()

    def test_the_derived_answer_is_recorded_so_it_is_derived_once(
        self, runner, hand_copied
    ):
        init(runner)
        config = (hand_copied / ".lore" / "config.toml").read_text(encoding="utf-8")
        assert 'init-agents = ["claude"]' in config

    def test_an_explicit_none_still_uninstalls(self, runner, hand_copied):
        init(runner, "--agent", "none", "--skills", "all", "--yes")
        assert entries(hand_copied, CLAUDE_SKILLS) == set()

    def test_a_project_with_no_agent_directory_installs_under_lore_skills(
        self, runner, legacy
    ):
        init(runner)
        assert entries(legacy, LORE_SKILLS) == set(current_skill_ids())
        assert not (legacy / "CLAUDE.md").exists()

    def test_a_directory_holding_only_the_users_own_skills_is_not_evidence(
        self, runner, legacy
    ):
        mine = legacy / CLAUDE_SKILLS / "my-own-skill" / "SKILL.md"
        mine.parent.mkdir(parents=True)
        mine.write_text("mine\n", encoding="utf-8")

        init(runner)

        assert entries(legacy, CLAUDE_SKILLS) == {"my-own-skill"}
        assert mine.read_text(encoding="utf-8") == "mine\n"

    def test_a_fresh_project_still_selects_no_agent(self, runner, fresh):
        init(runner)
        assert not (fresh / "CLAUDE.md").exists()
        assert entries(fresh, LORE_SKILLS) == set(current_skill_ids())


class TestARemovalSaysWhichKindItIs:
    """A retirement and an uninstall must not read identically.

    "Retired — port your edits into its successor" and "this file moved to
    another directory" call for opposite responses from the reader, so a
    removal report that renders both as a bare path tells nobody anything.
    """

    def test_an_uninstall_names_where_the_skill_went(self, runner, hand_copied):
        output = init(runner, "--agent", "none", "--skills", "all", "--yes").output

        # `inquest` is current, not retired: it is leaving `.claude/skills/`
        # only because the answer moved the install root.
        reported = removals(output)
        moved = f"{CLAUDE_SKILLS}/inquest/SKILL.md"
        assert moved in reported, reported
        assert reported[moved] is not None
        assert LORE_SKILLS in reported[moved]

    def test_a_retirement_still_names_its_reason(self, runner, hand_copied):
        output = init(runner, "--agent", "none", "--skills", "all", "--yes").output
        retired = retired_alias("update-doctrine")
        reported = removals(output)

        assert reported[f"{CLAUDE_SKILLS}/{retired}/SKILL.md"]

    def test_a_retirement_names_its_successor(self, runner, hand_copied):
        output = init(runner, "--agent", "none", "--skills", "all", "--yes").output
        retired = retired_alias("update-doctrine")
        reason = removals(output)[f"{CLAUDE_SKILLS}/{retired}/SKILL.md"]

        assert ledger_successor(retired) in reason


# ---------------------------------------------------------------------------
# The second door to the same room — a recorded answer Lore cannot read
# ---------------------------------------------------------------------------
#
# Smoke round 7, N1. The empty-agent guard tells "explicitly no agent" apart
# from "nobody said", and one of its two ways of saying "explicitly" is an
# empty list recorded in `.lore/config.toml`. It tested `config.recorded_keys`
# — presence of the key — while the value came from `load_config`, which is
# fail-soft and coerces anything unusable to the built-in default `[]`. So a
# config Lore could not parse landed in the branch reserved for a deliberate
# choice, and one typo uninstalled every skill on exit 0.
#
# Two properties, because guarding each route one at a time is how the same
# outcome was reached twice: a value the loader threw away is not an answer,
# and — whatever produced it — a plan that uninstalls everything has to be
# stated by the run that performs it.


UNUSABLE_RECORDED_ANSWERS: dict[str, str] = {
    "a typo for a known id": 'init-agents = ["cluade"]\n',
    "a known id beside an unknown one": 'init-agents = ["claude", "windsurf"]\n',
    "numbers rather than ids": "init-agents = [1, 2]\n",
    "a bare string rather than a list": 'init-agents = "claude"\n',
    "a number rather than a list": "init-agents = 42\n",
}
"""Every `init-agents` value smoke round 7 reached the uninstall through."""


def record(project_dir: Path, line: str) -> None:
    """Append a settings line to the project's `.lore/config.toml`."""
    config = project_dir / ".lore" / "config.toml"
    config.write_text(config.read_text(encoding="utf-8") + line, encoding="utf-8")


@pytest.mark.parametrize(
    "line",
    list(UNUSABLE_RECORDED_ANSWERS.values()),
    ids=list(UNUSABLE_RECORDED_ANSWERS),
)
class TestAnUnusableRecordedAnswerIsNotAnAnswer:
    """A config Lore cannot understand must never authorise a destructive act."""

    def test_the_agent_directory_is_not_emptied(self, runner, hand_copied, line):
        record(hand_copied, line)

        init(runner)

        assert entries(hand_copied, CLAUDE_SKILLS) == set(current_skill_ids())

    def test_the_instruction_file_survives(self, runner, hand_copied, line):
        record(hand_copied, line)

        init(runner)

        assert (hand_copied / "CLAUDE.md").is_file()

    def test_the_evidence_decides_instead_and_is_recorded(
        self, runner, hand_copied, line
    ):
        record(hand_copied, line)

        init(runner)

        config = (hand_copied / ".lore" / "config.toml").read_text(encoding="utf-8")
        assert 'init-agents = ["claude"]' in config

    def test_the_unusable_value_is_still_reported_on_stderr(
        self, runner, hand_copied, line, monkeypatch
    ):
        """Rejecting the value silently would leave nobody anything to fix."""
        import lore.config

        # The warning fires once per process and this suite shares one, so the
        # latch is cleared to ask about *this* run rather than an earlier one.
        monkeypatch.setattr(lore.config, "_warned", False)
        record(hand_copied, line)

        result = init(runner)

        assert "init-agents" in result.stderr


# ---------------------------------------------------------------------------
# The backstop — an uninstall nobody asked for on this run
# ---------------------------------------------------------------------------


class TestAnUnstatedTotalUninstallIsRefused:
    """Deselecting every agent is destructive, so the run that does it says so.

    The empty selection recorded in `.lore/config.toml` used to be the second
    way of stating it. It is not a statement about *this* run — it is a value
    in a file, and smoke round 7 wrote one there by accident, twice, through a
    fail-soft default. So the recorded answer alone now stops, and the flag
    that means it goes ahead.
    """

    @pytest.fixture()
    def recorded_empty(self, hand_copied) -> Path:
        record(hand_copied, "init-agents = []\n")
        return hand_copied

    def run(self, runner, *args):
        from lore.cli import main

        return runner.invoke(main, ["init", *args])

    def test_the_run_stops(self, runner, recorded_empty):
        assert self.run(runner).exit_code == 1

    def test_nothing_is_removed(self, runner, recorded_empty):
        before = entries(recorded_empty, CLAUDE_SKILLS)

        self.run(runner)

        assert entries(recorded_empty, CLAUDE_SKILLS) == before
        assert before

    def test_the_message_names_the_flag_that_states_it(self, runner, recorded_empty):
        assert "--agent none" in self.run(runner).output

    def test_the_message_names_where_the_empty_selection_came_from(
        self, runner, recorded_empty
    ):
        output = self.run(runner).output

        assert "init-agents" in output
        assert "config.toml" in output

    def test_the_message_names_the_agent_it_would_have_dropped(
        self, runner, recorded_empty
    ):
        assert "claude" in self.run(runner).output

    def test_no_traceback_reaches_the_terminal(self, runner, recorded_empty):
        result = self.run(runner)

        assert "Traceback" not in result.output + result.stderr

    def test_stating_it_on_the_run_goes_ahead(self, runner, recorded_empty):
        result = self.run(runner, "--agent", "none", "--skills", "all", "--yes")

        assert result.exit_code == 0, result.output
        assert entries(recorded_empty, CLAUDE_SKILLS) == set()

    def test_the_flag_that_keeps_the_agent_also_goes_ahead(
        self, runner, recorded_empty
    ):
        result = self.run(runner, "--agent", "claude", "--skills", "all", "--yes")

        assert result.exit_code == 0, result.output
        assert entries(recorded_empty, CLAUDE_SKILLS) == set(current_skill_ids())

    def test_a_dry_run_shows_the_refusal_beside_the_removals(
        self, runner, recorded_empty
    ):
        result = self.run(runner, "--dry-run")

        assert "--agent none" in result.output
        assert "Remove" in result.output

    def test_a_project_with_nothing_installed_for_an_agent_is_untouched(
        self, runner, legacy
    ):
        """No evidence, nothing to uninstall — the guard has no reason to fire."""
        record(legacy, "init-agents = []\n")

        result = self.run(runner)

        assert result.exit_code == 0, result.output
        assert entries(legacy, LORE_SKILLS) == set(current_skill_ids())

    def test_a_second_run_after_a_stated_uninstall_is_not_refused(
        self, runner, recorded_empty
    ):
        """The steady state a stated `--agent none` leaves behind still runs."""
        self.run(runner, "--agent", "none", "--skills", "all", "--yes")

        result = self.run(runner)

        assert result.exit_code == 0, result.output

    def test_the_python_api_refuses_the_same_plan(self, runner, recorded_empty):
        from lore import api

        before = entries(recorded_empty, CLAUDE_SKILLS)
        plan = api.plan_init(project_root=recorded_empty)
        with pytest.raises(ValueError) as raised:
            api.apply_init(plan)

        assert "--agent none" in str(raised.value)
        assert entries(recorded_empty, CLAUDE_SKILLS) == before


# ---------------------------------------------------------------------------
# A current skill the project edited, on a project with no manifest
# ---------------------------------------------------------------------------
#
# Smoke round 7, N5. The legacy fallback admits a path only when its bytes match
# one Lore shipped, so an edited **current** skill is admitted by nothing —
# editing it is the disqualification. The run then reported
#
#     ! Kept  skills/start-quest/SKILL.md
#             not installed by Lore
#
# about a file the previous release installed. The two edited *retired* skills
# in the same run get the true wording, because Lane L widened the fallback for
# them; a current path had no such route. Same false-statement shape as round
# 6's F8, which was fixed on the manifest path and not on this one.


class TestAnEditedCurrentSkillIsNotDisowned:
    """Whose file it is and whose bytes they are are two questions.

    Round 7's N5 was the first answered with the second: an edited current
    skill on a legacy project read `not installed by Lore`. Under the ownership
    ruling only the first question is ever asked, and the answer here is Lore's
    — so the file is taken back rather than described.
    """

    @pytest.fixture()
    def edited(self, hand_copied) -> Path:
        target = hand_copied / CLAUDE_SKILLS / "inquest" / "SKILL.md"
        assert target.is_file(), "inquest is not a current skill in this fixture"
        target.write_text("# mine now\n", encoding="utf-8")
        return hand_copied

    def test_the_run_no_longer_says_lore_never_installed_it(self, runner, edited):
        output = init(runner).output

        assert f"{CLAUDE_SKILLS}/inquest/SKILL.md" not in kept(output)
        assert reconcile.NOT_INSTALLED_BY_LORE not in output

    def test_it_is_taken_back_rather_than_reported(self, runner, edited):
        init(runner)

        target = edited / CLAUDE_SKILLS / "inquest" / "SKILL.md"
        assert target.read_text(encoding="utf-8") != "# mine now\n"

    def test_the_row_says_where_a_skill_of_their_own_belongs(self, runner, edited):
        summary = init(runner, "--dry-run").output
        row = next(
            line
            for line in summary.splitlines()
            if f"{CLAUDE_SKILLS}/inquest/SKILL.md" in line
        )
        assert reconcile.EDIT_DISCARDED in row
        assert CLAUDE_SKILLS in row.split()[-1]

    def test_a_file_lore_never_shipped_still_reads_as_not_installed(
        self, runner, hand_copied
    ):
        """The wording still distinguishes the two cases it exists to
        distinguish: a path Lore installs to, holding a file it never put
        there."""
        mine = hand_copied / CLAUDE_SKILLS / "inquest" / "NOTES.md"
        mine.write_text("mine\n", encoding="utf-8")

        init(runner)

        assert mine.read_text(encoding="utf-8") == "mine\n"


# ---------------------------------------------------------------------------
# The agent doc a pre-manifest release installed
# ---------------------------------------------------------------------------


class TestTheLegacyAgentDoc:
    """`.lore/LORE-AGENT.md` is a file Lore installed, at a hash Lore shipped.

    Left behind, it goes on advertising the skills the same run just deleted —
    and it is the file the coding agent reads.
    """

    def test_a_pristine_legacy_agent_doc_is_replaced(self, runner, legacy):
        output = init(runner).output

        assert shown(AGENT_DOC) not in kept(output)
        assert (legacy / AGENT_DOC).read_text(encoding="utf-8") != OLD_AGENT_DOC

    def test_an_edited_agent_doc_is_replaced_too(self, runner, legacy):
        """`.lore/` is Lore's directory, and this is Lore's file inside it.

        There is no second copy of it a project could keep, so the row states
        what happened and names no alternative.
        """
        mine = OLD_AGENT_DOC + "\nMy own note.\n"
        (legacy / AGENT_DOC).write_text(mine, encoding="utf-8")

        output = init(runner).output

        assert shown(AGENT_DOC) not in kept(output)
        assert (legacy / AGENT_DOC).read_text(encoding="utf-8") != mine

    def test_the_shipped_table_carries_the_agent_doc(self):
        assert reconcile.load_legacy_hashes().get(AGENT_DOC)


class TestTheHandCopiedSkillsGitignore:
    """The listing the old docs copied into `.claude/skills/` is Lore's file.

    It says so in its own header, and leaving it there un-ignores every skill
    this release installs while pointing thirteen entries at deleted ones.
    """

    def test_it_is_rewritten_with_the_installed_skills(self, runner, hand_copied):
        init(runner)

        listing = (hand_copied / CLAUDE_SKILLS / ".gitignore").read_text(
            encoding="utf-8"
        )
        for skill_id in current_skill_ids():
            assert f"{skill_id}/\n" in listing

    def test_the_stale_listing_is_gone_from_the_lore_tree(self, runner, hand_copied):
        init(runner)
        assert not (hand_copied / LORE_SKILLS / ".gitignore").exists()

    def test_the_shipped_table_carries_the_skills_gitignore(self):
        assert reconcile.load_legacy_hashes().get(f"{LORE_SKILLS}/.gitignore")


# ---------------------------------------------------------------------------
# An edited retired skill — the one file whose successor actually matters
# ---------------------------------------------------------------------------


class TestAnEditedRetiredSkill:
    """The file with the user's own work in it is the one that needs the pointer.

    It is Lore's file at a name no release ships any more, so it goes; keeping
    it left the agent loading a retired skill beside its replacement for good.
    What the removal owes its reader is the successor, which is exactly what
    the report used to withhold from this one row (round 3, defect 4).
    """

    @pytest.fixture()
    def edited(self, legacy):
        retired = retired_alias("update-doctrine")
        target = legacy / LORE_SKILLS / retired / "SKILL.md"
        target.write_text(
            target.read_text(encoding="utf-8") + "\nMy own note.\n", encoding="utf-8"
        )
        return legacy, f"{LORE_SKILLS}/{retired}/SKILL.md", retired

    def test_it_is_reported(self, runner, edited):
        _, path, _ = edited
        assert shown(path) in removals(init(runner).output)

    def test_the_report_names_the_successor(self, runner, edited):
        _, path, retired = edited
        detail = removals(init(runner).output)[shown(path)]
        assert detail is not None
        assert ledger_successor(retired) in detail

    def test_the_report_admits_the_edit_went_with_it(self, runner, edited):
        _, path, _ = edited
        assert reconcile.EDIT_DISCARDED in removals(init(runner).output)[shown(path)]

    def test_it_is_removed(self, runner, edited):
        project, path, _ = edited

        init(runner)

        assert not (project / path).exists()

    def test_skip_removes_it_too(self, runner, edited):
        project, path, _ = edited
        init(runner, "--on-conflict", "skip", "--yes")
        assert not (project / path).exists()

    def test_a_users_own_skill_at_a_path_lore_never_shipped_is_still_ignored(
        self, runner, legacy
    ):
        mine = legacy / LORE_SKILLS / "team-review" / "SKILL.md"
        mine.parent.mkdir(parents=True)
        mine.write_text("ours\n", encoding="utf-8")

        output = init(runner).output

        assert mine.read_text(encoding="utf-8") == "ours\n"
        assert shown(f"{LORE_SKILLS}/team-review/SKILL.md") not in kept(output)


# ---------------------------------------------------------------------------
# Rollback — an older binary rewrote the state this one trusts
# ---------------------------------------------------------------------------


class TestAnOlderReleaseTouchedTheProjectSince:
    """A manifest is a record of one run, not proof of what is on disk.

    Rolling back to an older `lore` and re-initialising reinstalls the retired
    skills and rewrites two current ones with older text. The manifest that the
    newer release then reads mentions none of it.
    """

    OLDER_INQUEST = b"# inquest\n\nThe text a release before this one shipped.\n"

    @pytest.fixture()
    def rolled_back(self, runner, legacy, legacy_table, table_rows):
        """Upgraded, then re-initialised by a release that predates the manifest."""
        stale = {}
        for current in ALIASED:
            retired = retired_alias(current)
            source = legacy / LORE_SKILLS / retired
            stale[retired] = {
                path.relative_to(source).as_posix(): path.read_bytes()
                for path in sorted(source.rglob("*"))
                if path.is_file()
            }

        init(runner, "--agent", "none", "--skills", "all", "--yes")

        # What the older binary put back: its own skill set, and its own text
        # over a skill this release still ships — bytes the historical table
        # records for that path, and the manifest just written does not.
        for retired, files in stale.items():
            for within, content in files.items():
                target = legacy / LORE_SKILLS / retired / within
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(content)
        (legacy / LORE_SKILLS / "inquest" / "SKILL.md").write_bytes(self.OLDER_INQUEST)
        table_rows[f"{LORE_SKILLS}/inquest/SKILL.md"].append(
            manifest.bytes_digest(self.OLDER_INQUEST)
        )
        legacy_table(table_rows)
        return legacy

    def test_the_reinstalled_retired_skills_are_removed(self, runner, rolled_back):
        init(runner, "--agent", "none", "--skills", "all", "--yes")

        for current in ALIASED:
            assert not (rolled_back / LORE_SKILLS / retired_alias(current)).exists()

    def test_a_current_skill_at_older_shipped_text_is_replaced(
        self, runner, rolled_back
    ):
        target = rolled_back / LORE_SKILLS / "inquest" / "SKILL.md"

        output = init(runner, "--agent", "none", "--skills", "all", "--yes").output

        assert target.read_bytes() != self.OLDER_INQUEST
        assert shown(f"{LORE_SKILLS}/inquest/SKILL.md") not in kept(output)


# ---------------------------------------------------------------------------
# The plan is the consent surface
# ---------------------------------------------------------------------------


class TestThePlanNamesEveryFileTheRunWrites:
    """`--help` promises the plan lists every file, and the confirm gate shows it.

    The seeded `default/` trees are about seventy files the run overwrites in
    place. A plan that omits them asks for consent to something else.
    """

    def test_the_plan_names_the_seeded_default_trees(self, runner, legacy):
        output = init(runner, "--dry-run").output
        for tree in ("knights/default", "artifacts/default", "doctrines/default"):
            assert tree in output, output

    def test_the_plan_writes_nothing(self, runner, legacy):
        before = {
            path.relative_to(legacy).as_posix(): path.read_bytes()
            for path in sorted(legacy.rglob("*"))
            if path.is_file()
        }

        init(runner, "--dry-run")

        after = {
            path.relative_to(legacy).as_posix(): path.read_bytes()
            for path in sorted(legacy.rglob("*"))
            if path.is_file()
        }
        assert after == before

    def test_every_path_the_run_writes_appeared_in_the_plan(self, runner, legacy):
        # The plan names paths from the repository root; an applied run names a
        # path inside `.lore/` relative to it. `shown` is that difference.
        planned = {shown(path) for path in plan_paths(init(runner, "--dry-run").output)}
        # "Created .lore/ directory" names the directory the rest go into, not
        # a file — the plan is a list of files.
        applied = written(init(runner).output) - {".lore/"}

        assert sorted(applied - planned) == []


class TestAFileTheReleaseNoLongerShips:
    """A seeded `default/` tree is Lore's own, so a file it stopped shipping is stale.

    The two oldest releases seeded artifacts at paths this one renamed. Left
    there, they fail `lore health` against a schema that has moved on.
    """

    def test_it_is_removed_from_the_seeded_tree(self, runner, legacy):
        orphan = legacy / ".lore" / "artifacts" / "default" / "codex" / "CODEX.md"
        orphan.parent.mkdir(parents=True, exist_ok=True)
        orphan.write_text("stale\n", encoding="utf-8")

        init(runner)

        assert not orphan.exists()

    def test_the_removal_is_reported(self, runner, legacy):
        orphan = legacy / ".lore" / "knights" / "default" / "gone.md"
        orphan.write_text("stale\n", encoding="utf-8")

        output = init(runner).output

        assert "knights/default/gone.md" in removals(output)

    def test_a_tree_of_the_users_own_is_untouched(self, runner, legacy):
        mine = legacy / ".lore" / "knights" / "team" / "reviewer.md"
        mine.parent.mkdir(parents=True, exist_ok=True)
        mine.write_text("ours\n", encoding="utf-8")

        init(runner)

        assert mine.read_text(encoding="utf-8") == "ours\n"

    def test_health_is_clean_after_the_prune(self, runner, legacy):
        from lore.cli import main

        orphan = (
            legacy
            / ".lore"
            / "artifacts"
            / "default"
            / "codex"
            / "technical"
            / "database"
            / "schemas"
            / "tasks.md"
        )
        orphan.parent.mkdir(parents=True, exist_ok=True)
        orphan.write_text(
            "---\nid: art-stale\ntitle: Stale\nrelated: []\n---\n\nStale.\n",
            encoding="utf-8",
        )

        init(runner)

        result = runner.invoke(main, ["health"])
        assert result.exit_code == 0, result.output
